#!/usr/bin/with-contenv bash

# This is an example service that would run for the feature
# It depends on init-services, the baseimage hook for start of all longrun services

exec \
    s6-setuidgid \
        user \
            /nix/var/nix/profiles/default/bin/nix-daemon
